# Generated by Django 3.2.3 on 2021-05-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('marcado', models.BooleanField(default=False)),
            ],
        ),
    ]
